

```{r}
options(scipen = 999)
```

```{r}
library(ggplot2)
library(tidyverse)

```
'''
# THE DATA https://docs.google.com/spreadsheets/d/e/2PACX-1vSgZnrr8yZ5Hj8-FfS_yZzgkG7VN1ywdS9QZtxdy-F3gaAZ8PXcq3NWUUEV0LYh9K_7Ye9uIxv_GkAl/pubhtml
'''

```{r}
data<- read_csv("country_pop_covid.csv")
                
```

```{r}
data$Country<- as.factor(data$Country)
```

```{r}
head(data,2)
```


```{r}
data
```


```{r}
data<-select(data,Country,Population,covid_cases)
```

```{r}
head(data)
```


```{r}
data<- data%>%
        gather("status", "number",2:3)
```

```{r}
data
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status, ),width = 0.7)+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  scale_y_log10()+
  ggtitle("Log 10")
```



```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  scale_y_log10()+
   guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Log 10")
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  scale_y_continuous(trans='log2')+
   guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Log 2")
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
   scale_y_sqrt()+
  ggtitle("Square Root")
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
 scale_y_continuous(breaks = c( 0,9000000,10000000,100000000,200000000,300000000))+
  ggtitle("Messing with the breaks")
```


# You can also create your own. See ?scales::trans_new
```{r}
?scales::trans_new
```


EXample of trans_new , thisone using cubed root

#https://stackoverflow.com/questions/49248937/in-rs-scales-package-why-does-trans-new-use-the-inverse-argument

```{r}
library(scales)
```

```{r}
cube_root <- function(x) x ^ (1/3)
cube <- function(x) x ^ 3
```

```{r}
trans_cube <- trans_new(name = "cube root",
                        transform = cube_root,
                        inverse = cube)
```

# applying a transform
ggplot(plot_data, aes(x = x, y = y)) +
  geom_point() +
  coord_trans(y = trans_cube)
  
```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Cubed Root")+
  coord_trans(y = trans_cube)
```


```{r}
quarter_root <- function(x) x ^ (1/4)
cube <- function(x) x ^ 4
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Quarter Root")+
  coord_trans(y = trans_cube)
```



```{r}
quarter_root <- function(x) x ^ (1/8)
cube <- function(x) x ^ 8
```

```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Eighth Root")+
  coord_trans(y = trans_cube)+
 
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
  ggtitle("Covid Cases as a Proportion of  Population ")+
  coord_trans(y = trans_cube)+
  scale_y_continuous(label=comma,breaks = c(50000, 5000000,000,100000000, 300000000))+
  theme_classic()+
      theme(axis.line.y = element_line(colour = 'black', size=1, linetype='solid'))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1,hjust = 0.99))+
  theme(axis.title.x = element_blank(),
          axis.title.y = element_blank())+
theme( # remove the vertical grid lines
           panel.grid.major.x = element_blank() ,
           # explicitly set the horizontal lines (or they will disappear too)
           panel.grid.major.y = element_line( size=.1, color="black" ) 
    )
 
```


```{r}
ggplot(data, aes(x=Country, y=number))+
      geom_col(aes(fill=status) , width = 0.7, position = position_stack(reverse = T))+
  theme(axis.text.x = element_text(angle = 45, vjust = 0.75,hjust = 0.9))+
  guides(fill = guide_legend(reverse = TRUE))+
  labs(title = "Covid Cases as Proportion of Population",
              subtitle = "",
              caption = "Datasource: Johns Hopkins Corona Resource Center")+
  coord_trans(y = trans_cube)+
  scale_y_continuous(label=comma,breaks = c(50000, 5000000,000,100000000, 300000000))+
  theme_classic()+
      theme(axis.line.y = element_line(colour = 'black', size=1, linetype='solid'))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1,hjust = 0.99))+
  theme(axis.title.x = element_blank(),
          axis.title.y = element_blank())+
theme( # remove the vertical grid lines
           panel.grid.major.x = element_blank() ,
           # explicitly set the horizontal lines (or they will disappear too)
           panel.grid.major.y = element_line( size=.1, color="black" ) 
    )
```


labs(title = ("Covid Cases as Proportion of Population",
        subtitle = "",
        caption = "Datasource: Johns Hopkins Corona Resource Center")



