---
title: "Corona_Countries_Pop_Adj"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
options(scipen = 999)
```

```{r}
library(ggplot2)
library(tidyverse)
library(gsheet)
library(choroplethr)
library(maps)
library(sf)
library("rnaturalearth")
library("rnaturalearthdata")
#
library(rworldmap)
#
require(maps)
require(ggmap)
library(maps)

```
# DATA NOVIA
#https://www.datanovia.com/en/blog/how-to-create-a-map-using-ggplot2/

```{r}
library(ggplot2)
library(dplyr)
require(maps)
require(viridis)
theme_set(
  theme_void()
  )
```


```{r}
world_map <- map_data("world")
```

```{r}
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "white")
```

#Map for specific regions


# Some EU Contries
some.eu.countries <- c(
  "Portugal", "Spain", "France", "Switzerland", "Germany",
  "Austria", "Belgium", "UK", "Netherlands",
  "Denmark", "Poland", "Italy", 
  "Croatia", "Slovenia", "Hungary", "Slovakia",
  "Czech republic"
)

```{r}
# Some EU Contries
some.eu.countries <- c(
  "Portugal", "Spain", "France", "Switzerland", "Germany",
  "Austria", "Belgium", "UK", "Netherlands",
  "Denmark", "Poland", "Italy"
)
```

```{r}
# Retrievethe map data
some.eu.maps <- map_data("world", region = some.eu.countries)
```

```{r}
# Compute the centroid as the mean longitude and lattitude
# Used as label coordinate for country's names
region.lab.data <- some.eu.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))
```




```{r}
ggplot(some.eu.maps, aes(x = long, y = lat)) +
  geom_polygon(aes( group = group, fill = region))+
  geom_text(aes(label = region), data = region.lab.data,  size = 3, hjust = 0.5)+
  scale_fill_viridis_d()+
  theme_void()+
  theme(legend.position = "none")
```

#Make a choropleth Map
#World map colored by life expectancy

```{r}
library("WHO")
library("dplyr")
```

#https://github.com/expersso/WHO

#https://github.com/expersso/WHO
```{r}
library(devtools)
install_github("expersso/WHO")
```










########3
```{r}
help("country_choropleth")
```


```{r}
country_pop<- read_csv("country_pop.csv")
```

```{r}
str(country_pop)
```

```{r}
par(mfrow = c(2,1))
```

```{r}
map("usa")
```

```{r}
map("europe")
```
 #https://medium.com/@jules.beley/making-a-map-with-eu-data-on-r-erasmus-exchanges-by-country-3f5734dcd4ff
 
 
#############
# https://medium.com/@jules.beley/making-a-map-with-eu-data-on-r-erasmus-exchange#s-by-country-3f5734dcd4ff

```{r}
world<-map_data("world ")
```

```{r}
library("WHO")
library("dplyr")
```


```{r}
who
```

```{r}
life.exp <- get_data("WHOSIS_000001")             # Retrieve the data
```



